name: Feature Request
description: Suggest an idea for this project
labels: ["Status : Opened 📬​", "Type : Feature Request 📝​​"]
body:
  - type: textarea
    id: request
    attributes:
      label: Details of the feature request
      description: Describe as much information as possible
      placeholder: What I'd like to see added, the elements I've seen that prove it can work
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Need quickly ?
      options:
        - No
        - Preferable
        - If possible quickly
        - Yes, it's urgent
      default: 0
