name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'        
#      - name: Copy IDF patch
#        run: | 
#          ls -l /app/
      
      - name: ESP-IDF build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.1
          target: esp32c6
          path: 'firmware'
          
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: |
      #       release/*
      - name: Archive build output artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            bootloader/bootloader.bin
            partition_table/partition-table.bin
            ota_data_initial.bin
            storage.bin
            TICMeter.bin
