name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: ESP-IDF build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.1
          target: esp32c6
          path: 'firmware'
          
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: |
      #       release/*
            # build/storage.bin
            #build/ota_data_initial.bin
      - name: test
        run: cd firmware  
      - name: test
        run: ls -l 
      - name: test
        run: ls -l firmware
      - name: test
        run: pwd
      - name: Archive build output artifacts
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: build
          path: firmware/build/bootloader/bootloader.bin
          
      - name: Archive build output artifacts
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: build
          path: ./firmware/partition_table/partition-table.bin

      - name: Archive build output artifacts
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: build
          path: |
            firmware/build/TICMeter.bin
            firmware/build/storage.bin
            firmware/build/ota_data_initial.bin
          if-no-files-found: error
          
      # - name: Archive build output artifacts
      #   uses: actions/upload-artifact@v3
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     name: build
      #     path: ./build/storage.bin
      #     if-no-files-found: error
          
      # - name: Archive build output artifacts
      #   uses: actions/upload-artifact@v3
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     name: build
      #     path: ./build/ota_data_initial.bin
      #     if-no-files-found: error
          
