name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - name: Copy IDF patch
        run: | 
          ls -l /app/
          ls -l /app/xmow49/
          ls -l /app/xmow49/LinkyTeleinfoESP32/
          ls -l /app/xmow49/LinkyTeleinfoESP32/patch
          mkdir -p /opt/esp/idf/components/esp_netif/include/
          mkdir -p /opt/esp/idf/components/esp_hw_support/
          cp /app/xmow49/LinkyTeleinfoESP32/firmware/patch/esp_netif_sntp.h /opt/esp/idf/components/esp_netif/include/esp_netif_sntp.h
          cp /app/xmow49/LinkyTeleinfoESP32/firmware/patch/sleep_modes.c /opt/esp/idf/components/esp_hw_support/sleep_modes.c
      
      - name: ESP-IDF build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.1
          target: esp32c6
          path: 'firmware'
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/*
