name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: ESP-IDF build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.1
          target: esp32c6
          path: 'firmware'
      - name: Create manifest
        run: |
          cd firmware/scripts
          python3 ./create_manifest.py
          
      - name: Release
        uses: softprops/action-gh-release@v1
        # Note:
        # If you get the error "Resource not accessible by integration",
        # The access rights are not sufficient, see
        # https://github.com/softprops/action-gh-release/issues/232#issuecomment-1131379440
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name:  ${{ steps.get_version.outputs.version-without-v }}
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          files: |
            firmware/build/bootloader/bootloader.bin
            firmware/build/partition_table/partition-table.bin
            firmware/build/TICMeter.bin
            firmware/build/storage.bin
            firmware/build/ota_data_initial.bin
